services:
  site:
    build:
      dockerfile: Dockerfile.dev
      context: .
      no_cache: true
    container_name: web
    restart: "no"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/marketplace
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ZiOqXb3gEu444v1/sXnfCM+ggqLo5F2hhq688xiLDMg=

  db:
    image: postgres:latest
    restart: "no"
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVE_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: "no"

volumes:
  pgadmin_data:
    name: pgadmin_data